### ISSUE TITLE
 Incompatible with the configured c2profile

### ISSUE THREAD

**Issue by shannaburns** [0xEr3bus/RdpStrike#1]
When I added the anti-kill effect setting，such as：
![image](https://github.com/0xEr3bus/RdpStrike/assets/156292454/e9e5e8d0-b017-4252-808d-41026cdd2b5a)
It will show the following error. 
![image](https://github.com/0xEr3bus/RdpStrike/assets/156292454/a2a35ab7-9655-4195-8968-93800fb5d44b)

Is it compatible with the configuration of c2profile?

**Comment by 0xEr3bus** [comment]
That's correct you are not supposed to transform the shellcode in the CobaltStrike Mallable profile. There is a section (`process-inject`) in the profile:
```bash
process-inject {
    set allocator "VirtualAllocEx";  # Important: Default implementation of MapViewSection will not work.

    transform-x64 {  # Do not transform the shellcode, like adding nops or replacing anything. 
        #prepend "\x90\x90\x90\x90\x90\x90\x90\x90\x90"; # NOP, NOP!
    }
    ...
}
``` 
This is because the shellcode will change its own protection using the `NtProtectVirtualMemory` syscall. If you use `MapViewSection` it will cause an `STATUS_SECTION_PROTECTION` Error. And `transform-x64` will cause issues in padding and shit.

However, the best option is to write our process injection technique as CobaltStrike is completely customizable. Closing the issue right now, please do open it if it still fails.
